server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/sharding_migrate?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Aa@121216